name: Compile PixivChan
on:
  push:
    branches: 
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  my-job:
    name: Build PixivChan 🚀
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Build
      run: export GOOS=windows; export GOARCH=amd64; go build -ldflags="-s -w" -o artifacts/PixivChan.exe
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PixivChan.exe
        path: ./artifacts
